name = "countify-api"
main = "src/index.ts"
compatibility_date = "2023-06-04"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
routes = ["api.countify.dev/*"]

[observability]
enabled = true
head_sampling_rate = 1

[placement]
mode = "off"

[define]
ENVIRONMENT = '"production"'

[durable_objects]
bindings = [{ name = "COUNTER", class_name = "Counter" }]

[[migrations]]
tag = "v1"                # Should be unique for each entry
new_classes = ["Counter"] # Array of new classes

[[kv_namespaces]]
binding = "CONFIG"
id = "19ecdcf903f242bc935bd4e8e5f31d7e"
preview_id = "38195bdce3e04a679558080b2de9bd86"
