name = "countify-api"
main = "src/index.ts"
compatibility_date = "2023-06-04"
usage_model = "unbound"
workers_dev = false
routes = ["api.countify.dev/*"]

[define]
ENVIRONMENT = '"production"'

[[kv_namespaces]]
binding = "CONFIG"
id = "19ecdcf903f242bc935bd4e8e5f31d7e"
preview_id = "38195bdce3e04a679558080b2de9bd86"
